name: drtimport
version: 2.0.0
homepage: https://github.com/bsutton/cli_tools_for_dart
description: An cli app to help you refactor you dart libraries because VSCode won't.
environment: 
  sdk: '>=2.5.0 <3.0.0'
dependencies: 
  args: ^1.6.0
  dcli: 1.2.1
  file_utils: ^0.1.3
  path: ^1.6.4
  pedantic: ^1.8.0
  yaml: ^2.2.0
  intl: ^0.16.0
  logger: ^0.9.1
  recase: ^3.0.0
dev_dependencies: 
  test: ^1.6.0
executables: 
  drtimport: main
