name: drtimport
version: 3.0.0
homepage: https://github.com/bsutton/cli_tools_for_dart
description: An cli app to help you refactor you dart libraries because VSCode won't.
environment: 
  sdk: '>=2.5.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^1.31.2
  file_utils: ^1.0.1
  path: ^1.6.4
  pedantic: ^1.8.0
  yaml: ^3.0.0
  intl: ^0.17.0
  logger: ^1.1.0
  recase: ^4.0.0
dev_dependencies: 
  test: ^1.6.0
executables: 
  drtimport: main
